include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - directives_ordering
    - sort_constructors_first
    - unawaited_futures
    - use_super_parameters

analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-raw-types: true
