name: focus_noise_app
description: A Flutter app that generates and mixes white, pink, brown noise and binaural beats on-device.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  audio_service: ^0.18.10
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1   # ← agregado
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/ogg/
    - assets/brand/app-icon-1024-white.png
    - assets/brand/focusnoise-mark-1024.png
    - assets/brand/app-icon-monochrome-432.png
    - assets/brand/play-store-icon-512.png
    - assets/brand/app-icon-foreground-1024.png
    - assets/brand/app-icon-foreground-512.png
    - assets/brand/app-icon-foreground-432.png
    - assets/brand/ic_notification_white_96.png

# === Configuración del generador de íconos ===
flutter_launcher_icons:
  android: true
  ios: true
  # iOS y fallback
  image_path_ios: "assets/brand/app-icon-1024-white.png"
  image_path: "assets/brand/app-icon-1024-white.png"
  remove_alpha_ios: true

  # Android Adaptive (Android 8+)
  adaptive_icon_foreground: "assets/brand/focusnoise-mark-1024.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_monochrome: "assets/brand/app-icon-monochrome-432.png"
  min_sdk_android: 21

flutter_native_splash:
  # Fondo splash (azul claro de tu app). Si lo quieres blanco: "#FFFFFF"
  color: "#64B5F6"

  # Solo el logo (sin palabras)
  image: assets/brand/app-icon-foreground-1024.png

  # Modo oscuro (mismo logo; fondo un poco más oscuro para contraste)
  color_dark: "#1565C0"
  image_dark: assets/brand/app-icon-foreground-1024.png

  # Android 12 requiere config específica
  android_12:
    color: "#64B5F6"
    image: assets/brand/app-icon-foreground-1024.png
    color_dark: "#1565C0"
    image_dark: assets/brand/app-icon-foreground-1024.png

  # Opcional: ajusta la escala si lo ves muy grande/pequeño (0.0–1.0)
  # android_gravity: center
  # ios_content_mode: center
  # image_scale: 0.20