name: FocusNoise
description: A Flutter app that generates and mixes white, pink, brown noise and binaural beats on-device.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  audio_service: ^0.18.10
  audio_session: ^0.1.18
  flutter_svg: ^2.0.9
  flutter_markdown: ^0.7.3
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/audio/ogg/
    - assets/brand/app-icon-1024-white.svg
    - assets/brand/focusnoise-mark-1024.png
    - assets/brand/app-icon-monochrome-432.svg
    - assets/brand/play-store-icon-512.svg
    - assets/brand/app-icon-foreground-1024.svg
    - assets/brand/app-icon-foreground-512.svg
    - assets/brand/app-icon-foreground-432.svg
    - assets/brand/ic_notification_white_96.svg
    - assets/legal/CREDITS.md

# === Configuración del generador de íconos ===
flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/brand/app-icon-1024-white.svg"
  image_path: "assets/brand/app-icon-1024-white.svg"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/brand/focusnoise-mark-1024.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_monochrome: "assets/brand/app-icon-monochrome-432.svg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#64B5F6"
  image: assets/brand/app-icon-foreground-1024.svg
  color_dark: "#1565C0"
  image_dark: assets/brand/app-icon-foreground-1024.svg
  android_12:
    color: "#64B5F6"
    image: assets/brand/app-icon-foreground-1024.svg
    color_dark: "#1565C0"
    image_dark: assets/brand/app-icon-foreground-1024.svg

gen-l10n:
  arb-dir: lib/l10n/generated
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  untranslated-messages-file: lib/l10n/generated/untranslated.json
  synthetic-package: false
